language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
before_start:
  - mkdir lib/
  - wget -P "lib/" http://urlForYourJar.jar
