name: Battlegrounds
version: 0.1-DEV
main: net.abstractiondev.mcbg.BattlegroundsPlugin
depend: [Vault, WorldEdit, WorldBorder]
commands:
  bg:
    description: Main command for Battlegrounds Plugin
    default: true
    usage: /bg